version: '3.8'

services:
  vegitable_order_app:
   build: .
   image: vegitable-app:v1.0.0
   container_name: vegitable
   ports:
     - "3000:3000"
   environment:
     - MONGODB_URI=mongodb://mongodb:27017/vegetable_order_app
    
   depends_on:
     - mongodb

  mongodb:
   image: mongo:latest
   container_name: mongodb
   ports:
     - "27017:27017"
