apiVersion: v1
kind: ConfigMap
metadata:
  name: veg-config
  namespace: sukhesh-ns

data:
  MONGO_URL: "mongodb://mongodb-service:27017/vegetable_order_app"
  MONGO_INITDB_DATABASE: "vegetable_order_app"
