apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-deployment
  namespace: sukhesh-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
      - name: ipl-container
        image: muralisocial123/ipl:latest
        ports:
        - containerPort: 3000
