apiVersion: apps/v1
kind: Deployment

metadata:
  name: veg-deployment
  namespace: sukhesh-ns
  labels:
    app: vegetable-order-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: vegetable-order-app

  template:
    metadata:
      labels:
        app: vegetable-order-app

    spec:
      containers:
      - name: vegetable-order-app

        image: sukhesh77/vegetable-order-app:v1

        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: veg-app-config
