apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: sukhesh-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: vegetable
  template:
    metadata:
      labels:
        app: vegetable
    spec:
      containers:
      - name: vegetable
        image: sukhesh77/vegetable-order-app:v1
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: veg-app-config
                key: MONGODB_URI
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: veg-app-config
                key: PORT
