apiVersion: v1
kind: ConfigMap
metadata:
  name: veg-app-config
  namespace: sukhesh-ns
data:
  MONGODB_URI: mongodb://veg-mongodb-service:27017/vegetable_order_app
  MONGO_INITDB_DATABASE: vegetable_order_app
