apiVersion: v1
kind: ConfigMap
metadata:
  name: veg-config
  namespace: sukhesh-ns
data:
  MONGODB_URL: "mongodb://veg-mongodb-service:27017/vegetable_order_app"
  MONGODB_INITDB_DATABASE: "vegetable_order_app"
