apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: sukhesh-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vegetable
  template:
    metadata:
      labels:
        app: vegetable
    spec:
      containers:
      - name: vegetable
        image: sukhesh77/vegetable-order-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: veg-config
              key: MONGO_URL
        
