apiVersion: v1
kind: ConfigMap
metadata:
  name: veg-app-config
  namespace: sukhesh-ns
data:
  MONGODB_URI: "mongodb://mongodb:27017/vegetable_order_app"
  PORT: "3000"
  MONGO_INITDB_DATABASE: "myDatabase"
