apiVersion: apps/v1
kind: Deployment
metadata:
  name: veg-deployment
  namespace: sukhesh-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: veg
  template:
    metadata:
      labels:
        app: veg
    spec:
      containers:
      - name: veg-container
        image: sukhesh77/vegetable-order-app:v1

        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: veg-config
                key: MONGODB_INITDB_DATABASE

          - name: MONGODB_URL
            valueFrom:
              configMapKeyRef:
                name: veg-config
                key: MONGODB_URL
      
