apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.mongodb.serviceName }}
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.app }}
    spec:
      containers:
        - name: {{ .Values.mongodb.containerName }}
          image: "{{ .Values.mongodb.repository }}:{{ .Values.mongodb.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: {{ .Values.mongodb.volume.name }}
              mountPath: {{ .Values.mongodb.volume.mountPath }}
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MONGO_INITDB_DATABASE
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mongodb.volume.name }}
      spec:
        accessModes:
          - {{ .Values.mongodb.volume.accessMode }}
        storageClassName: {{ .Values.storageClass.name }}
        resources:
          requests:
            storage: {{ .Values.mongodb.volume.size }}
